# Generated by Django 4.2.14 on 2024-07-19 11:45

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_options_remove_comment_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=mdeditor.fields.MDTextField(max_length=300, verbose_name='正文'),
        ),
    ]
