# Generated by Django 4.2.14 on 2024-07-17 12:56

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='content'),
        ),
    ]
